tools:
    php_sim:
        enabled: true
        min_mass: 16
        filter:
            excluded_paths:
                - 'app/*'
                - 'web/*'
                - '*Extension.php*'
                - '*Test*'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'app/*'
                - 'web/*'
                - '*Extension.php*'
                - '*Test*'
            paths: {  }
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'app/*'
                - 'web/*'
                - '*Extension.php*'
                - '*Test*'
            paths: {  }
        path_configs: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'app/*'
                - 'web/*'
                - '*Extension.php*'
                - '*Test*'
            paths: {  }
filter:
    excluded_paths:
        - 'app/*'
        - 'web/*'
        - '*Extension.php*'
        - '*Test*'
    paths: {  }
application:
    type: symfony2
    environment:
        hosts: {  }
        variables: {  }
        mysql: false
        postgresql: true
        redis: true
        elasticsearch: false
        rabbitmq: false
        mongodb: true
        neo4j: false
        memcached: false