imports:
    - { resource: config_dev.yml }

parameters:
    mxt_core.torrent.client.kickAss.class: MXT\CoreBundle\Test\Services\Client\Torrent\KickAss
    mxt_core.torrent.folder: "%kernel.root_dir%/../src/MXT/TransmissionBundle/Test/Files"

services:
    mxt_notification.subscriber.notification_subscriber:
        class: MXT\NotificationBundle\Test\Stub\NotificationSubscriber
        tags:
            - { name: kernel.event_subscriber }

liip_functional_test: ~

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine_mongodb:
    default_database: %mongodb_database%_test