mxt_notification:
    resource: "@MXTNotificationBundle/Resources/config/routing.yml"
    prefix:   /

mxt_transmission:
    resource: "@MXTTransmissionBundle/Resources/config/routing.yml"
    prefix:   /

mxt_core:
    resource: "@MXTCoreBundle/Resources/config/routing.yml"
    prefix:   /
