parameters:
    kickass.api:
      url: http://katproxy.com/json.php
      filters:
        - q #(Key)
        - field #(Order)
        - page #(Page)
    kickass.timeout:
      response: 10
      connection: 10
    kickass.search.fields:
      size: size
      files : files_count
      age   : time_add
      seed  : seeders
      leech : leecher