parameters:
    kickass.api:
      url: http://katproxy.com/json.php
      filters:
        - q #(Key)
        - field #(Order)
        - page #(Page)
    kickass.timeout:
      response: 10
      connection: 10
    kickass.search.fields:
      time_add: Age
      size: Size
      files_count: Files Count
      seeders: Seeders
      leechers: Leechers