parameters:
  mxt_transmission.transmission.class: MXT\TransmissionBundle\Services\MXTTransmission
  mxt_transmission.show.class: MXT\TransmissionBundle\Services\Process\TransmissionShow

services:
  mxt_transmission.transmission:
    class: %mxt_transmission.transmission.class%
    arguments:
      host: %transmission_host%
      port: %transmission_port%

  mxt_transmission.show:
    class: %mxt_transmission.show.class%
