parameters:
    mxt_core.torrent.folder: "%kernel.root_dir%/datas/Torrent"
    mxt_core.httpclient.class: MXT\CoreBundle\Services\MXTClient
    mxt_core.download.torCache.class: MXT\CoreBundle\Services\Download\TorCache
    mxt_core.torrent.client.kickAss.class: MXT\CoreBundle\Services\Client\Torrent\KickAss

services:
    mxt_core.httpclient:
       class: %mxt_core.httpclient.class%
    mxt_core.download.torCache:
      class: %mxt_core.download.torCache.class%
      arguments:
        client: @mxt_core.httpclient
        folder: %mxt_core.torrent.folder%
    mxt_core.torrent.client.kickAss:
        class: %mxt_core.torrent.client.kickAss.class%
        arguments:
              container: @service_container
              client: @mxt_core.httpclient